### PR TITLE
Feat/bal main navigation

### PR DESCRIPTION
**Pull request by madaluca**

### CODE REVIEW

**Review by hirsch88 — CHANGES_REQUESTED** [review]
This PR can not be merged until the below criteria have met!

1. atomic design
  - meta navigation with the blue background only for tablet and bigger
    - has a left and a right side like the navbar component
  - meta-mobile-head with logo and some action buttons like search login and burger menu
  - meta-mobile-foot with the other action like phone, language, map and must be sticky

  - main navigation with the white background only for tablet and bigger
  - main-mobile white background with link list and accordions

2. one date structure
  - less error like in example meta has Tab A but not on mobile

3. documentation
  - each prop needs to be documented
  - make good stories, which are matching the figma. not Tab A long text and so on.

That's how @mladenplaninicic and @hirsch88 me would do it, so that it needs less markup and is simpler for others to reuse.

Have a look at `bal-select` and the mutation observer. Same logic with the bal-select-options. @fabio-tedesco hope you remember that from our meeting 2 weeks ago ;-)


```html
<!-- Usage example -->
<bal-navigation>
  <bal-navigation-levels> <!-- hidden in the dom but can be grabbed by the mutation observer -->
    <bal-navigation-meta-level label="Private" link="http://" linkLabel="Zur Privatkundenübersicht">
      <bal-navigation-main-level label="Versichern" link="http://" linkLabel="Alle Versicherungslösungen">
        <bal-navigation-block-level label="Wohnen & Recht" link="http://">
          <bal-navigation-block-item label="Haushaltsversicherung" link="http://"></bal-navigation-block-item>
        </bal-navigation-block-level>
        <bal-navigation-block-level color="grey" label="Services">
          <bal-navigation-block-item label="Beratung vereinbaren" link="http://"></bal-navigation-block-item>
        </bal-navigation-block-level>
      </bal-navigation-main-level>
    </bal-navigation-meta-level>
    <bal-navigation-meta-level label="Unternehmen" link="http://" linkLabel="Zur Unternehmensübersicht">
      ...
    </bal-navigation-meta-level>
  </bal-navigation-levels>

  <div slot="meta-actions">
    <bal-button>Login</bal-button>
    ...
  </div>
  <div slot="meta-mobile-head">
    <bal-button>Login</bal-button>
    ...
  </div>
  <div slot="meta-mobile-foot">
    ...
  </div>
</bal-navigation>

--------------------------
<!-- implementation of the bal-navigation component -->
<Host>
  <bal-meta-navigation class="is-hidden-mobile"> <!-- only visible from tablet and bigger -->
    <bal-meta-navigation-start>
      tabs... create from the levels
    </bal-meta-navigation-start>
    <bal-meta-navigation-end>
      <slot name="meta-actions"></slot>
    </bal-meta-navigation-end>
  </bal-meta-navigation>

  <bal-main-navigation> <!-- only visible from tablet and bigger -->
    build up content from levels
  </bal-main-navigation>

  <div class="is-hidden-tablet"> <!-- only visible on mobile -->
    <bal-meta-mobile-head>
      <slot name="meta-mobile-head"></slot>
      burger button to open
    </bal-meta-mobile-head>
    <div>
      <bal-main-mobile>
        list... create from the levels
      </bal-main-mobile>
      <bal-meta-mobile-foot><!-- sticky -->
        <slot name="meta-mobile-foot"></slot>
      </bal-meta-mobile-foot>
    </div>
  </div>
</Host>
```

**Comment by Gagne87** [comment]
Unfortunately the padding-bottom in the fly-out is still wrong. Should be 40px instead of the 24px used in the implementation. Thanks for adapting.

**Comment by fabio-tedesco** [comment]
> Unfortunately the padding-bottom in the fly-out is still wrong. Should be 40px instead of the 24px used in the implementation. Thanks for adapting.

hi there. this is the old deprecated branch of the main navigation

**Comment by Gagne87** [comment]
Also one more thing to clarify that I don't see in the implementation yet: 

- The main navigation is not sticky yet -> will that be added?

**Pull request closed without merging**
