### PR TITLE
feat(bal-snackbar): added richtext flag

### PR DESCRIPTION
**Pull request by madaluca**
Closes #

{{added a flag for the rich text}}

## Acceptance Criteria

- [ ] Design Review by @Gagne87, @clastzoo
- [ ] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- [ ] Visual test done by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
- [ ] Functional test done by @hirsch88, @nobilo, @mladenplaninicic
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [ ] Chrome
        - [ ] Edge
        - [ ] Safari
        - [ ] Firefox
    - Tablet
        - [ ] iPad (Landscape / Portrait)
    - Mobile
        - [ ] Safari iOS
        - [ ] Chrome Preview

### CODE REVIEW

**Review by mladenplaninicic — APPROVED** [review]

**Review by nobilo — APPROVED** [review]

**Review by mladenplaninicic — CHANGES_REQUESTED** [review]
we can't merge this pr

**Comment by joachimprinzbach** [comment]
> we can't merge this pr

why?

**Comment by hirsch88** [comment]
@joachimprinzbach because we try to avoid conditional rendering and names slots, since we had trouble with them using proxy libs like angular

**Comment by hirsch88** [comment]
Fixe by other pr

**Pull request closed without merging**
